### ISSUE TITLE
Tensorflow Installation on Apple Silicon Macbook Failed

### ISSUE THREAD

**Issue by sakshamprakash01** [AASD4011-2023-spring/aasd4011-2023-spring#5]
Due to CPU architectural differences, TensorFlow has a different method to install.

**Comment by vijay-karthik-b** [comment]
**Found Solution**

Check out the below link for the steps to install Tensorflow in Mac:

https://developer.apple.com/metal/tensorflow-plugin/

**Comment by sakshamprakash01** [comment]
Solution:

Anaconda does not seem to be working as of writing this. MiniConda is working so we will use that.

1. Download the MiniConda executable script from here- https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh (Sourced from the above link by Apple).

2. Copy the downloaded file to your $HOME directory. This can be done by executing the following commands in a new terminal-
`sudo cp ~//Downloads/<name_of_downloaded_file.sh> ~/`

3. Execute the script by running bash `~/<name_of_downloaded_file.sh> -b -p $HOME/miniconda`

4. Activate the Miniconda's base environment by running `source ~/miniconda/bin/activate`

5. Execute the following command to create a new environment named 'tensorflow'-
`conda create -n tensorflow python=3.10.10`

6. Activate the environment- `conda activate tensorflow`

7. Install the packages- 
`conda install -c apple tensorflow-deps`
`python -m pip install tensorflow-macos`
`python -m pip install tensorflow-metal`

8. Install most updated numpy-
`pip install -U numpy`

9. Install other packages (Optional, but recommended for class)-
`pip install ipykernel tensorboard matplotlib nbconvert`

10. Try running the 'test_tensorflow.ipynb' file with this environment activated. It should work.

NOTE: (base) environments are important. Anaconda has its own base environment and Miniconda has its separate one. Activating any sub-environment like 'tensorflow' requires you to have the base environment of the respective environment manager (Anaconda or Miniconda) activated. This implies that having activated Miniconda's base environment, you will not be able to activate Anaconda's other environments and vice-versa.
To activate Miniconda's base environment on any new shell, use this command- `source ~/miniconda/bin/activate`

**Comment by RanFeldesh** [comment]
Thank you @vijay-karthik-b  and @sakshamprakash01 ,

Thanks for sharing the official recommendation by Apple. Indeed, given this is the recommended one by Apple, it's a great idea to follow it. 
Next steps:
* In case we would like to incorporate this into `setup.py`, I wonder if removing the dependency on Miniconda, and just use `pip` and the native `venv` would be possible. 
* If someone is interested to contribute a PR - the link to the official link you shared here can be shared as part of the setup README file, with a brief explanation. Issue: https://github.com/AASD4011-2023-spring/aasd4011-2023-spring/issues/11

Thank you folks !

**Comment by sakshamprakash01** [comment]
> In case we would like to incorporate this into setup.py, I wonder if removing the dependency on Miniconda, and just use pip and the native venv would be possible.

Unfortunately, as I mentioned in the first paragraph of my solution above, the "tensorflow-deps" is only available in conda package-manager and is officially supported by Apple with MiniConda. I did try using venv initially but after several failed attempts, I resorted to the above solution.

> If someone is interested to contribute a PR - the link to the official link you shared here can be shared as part of the setup README file, with a brief explanation. Issue: https://github.com/AASD4011-2023-spring/aasd4011-2023-spring/issues/11

Yes, we shall update the installation instructions. Continuing the conversation on that issue.
