### ISSUE TITLE
Solved: "torch==2.0.0+cpu" Error on Intel Macs when installing pytorch venv

### ISSUE THREAD

**Issue by Kawians** [AASD4011-2023-spring/aasd4011-2023-spring#7]
Hi everyone,

I had a problem installing pytorch venv and the error was related to "torch==2.0.0+cpu" in this stage of installation instructions:

Install the packages: `pip install -r requirements_pytorch_cpu.txt`
<img width="914" alt="image" src="https://github.com/AASD4011-2023-spring/aasd4011-2023-spring/assets/115752969/35745702-2b25-420c-bca4-1d3e493432d7">

To solve this problem, you can edit the "requirements_pytorch_cpu" txt file and delete the "+cpu" term.

<img width="678" alt="image" src="https://github.com/AASD4011-2023-spring/aasd4011-2023-spring/assets/115752969/62be23df-203f-43dc-b124-e25cc30757fa">

I will also attach the modified file.
[requirements_pytorch_cpu.txt](https://github.com/AASD4011-2023-spring/aasd4011-2023-spring/files/11457368/requirements_pytorch_cpu.txt)

Good Luck,

**Comment by sakshamprakash01** [comment]
Thanks for the contribution!

**Comment by sakshamprakash01** [comment]
@Kawians I am adding your requirements file as a contribution to the repository to be available for everybody!
Could you please clarify which architecture of cpu your macbook is? Is it intel or apple silicon?
Thank you so much!

**Comment by Kawians** [comment]
> @Kawians I am adding your requirements file as a contribution to the repository to be available for everybody!
> Could you please clarify which architecture of cpu your macbook is? Is it intel or apple silicon?
> Thank you so much!

@sakshamprakash01 That would be great Saksham, many thanks. 
It’s intel. I also mentioned intel in topic title to be searchable.

**Comment by athiradevan** [comment]
@Kawians Thank you for this. It worked for me. You did a good job.
