### ISSUE TITLE
Autograd env doesn't have numpy and torch for Assignment #2

### ISSUE THREAD

**Issue by RogerSinghChugh** [AASD4011-2023-spring/aasd4011-2023-spring#8]
Autograd doesn't have have numpy and torch in its env. Hence its giving an error while grading the tests.
![ss1](https://github.com/AASD4011-2023-spring/aasd4011-2023-spring/assets/35698080/a3b30c9e-5fda-47ca-8b92-c07a6ce9a1b1)
![ss2](https://github.com/AASD4011-2023-spring/aasd4011-2023-spring/assets/35698080/2188ec7f-76bb-4a5a-8b46-8a5b266c4c96)

**Comment by sakshamprakash01** [comment]
Thanks for bringing it up! This has been fixed @RogerSinghChugh.
